import type { Nitro } from "nitro/types";
import type { WranglerConfig } from "./types.ts";
import { join } from "pathe";
import { writeFile, prettyPath } from "../_utils/fs.ts";
import { resolveExportsEntry } from "./entry-exports.ts";
import { readWranglerConfig } from "./utils.ts";

export interface CloudflareDevWorker {
  entry: string;
  exports: Record<string, { type: "DurableObject" | "class" }>;
}

/**
 * Composes a dev worker entry that statically re-exports the app's Cloudflare
 * classes referenced by wrangler bindings (Durable Objects, Workflows) next to
 * the dev worker handlers — the dev counterpart of `setupEntryExports`.
 */
export async function composeCloudflareDevWorker(
  nitro: Nitro,
  devWorkerEntry: string
): Promise<CloudflareDevWorker | undefined> {
  const boundClasses = await getBoundClasses(nitro);
  const boundClassNames = Object.keys(boundClasses);
  if (boundClassNames.length === 0) {
    return;
  }

  const exportsEntry = resolveExportsEntry(nitro);
  if (!exportsEntry) {
    nitro.logger.warn(
      `[cloudflare] Wrangler config references the \`${boundClassNames.join("`, `")}\` class(es) but no Cloudflare exports entry was found (\`cloudflare.exports\` or \`exports.cloudflare.ts\`). They will not be available in dev.`
    );
    return;
  }

  const outDir = join(nitro.options.buildDir, "cloudflare-dev");

  let availableExports: string[];
  try {
    availableExports = await bundleExportsEntry(exportsEntry, join(outDir, "exports.mjs"));
  } catch (error) {
    nitro.logger.error(
      `[cloudflare] Failed to bundle \`${prettyPath(exportsEntry)}\`. Its exports will not be available in dev.`,
      error
    );
    return;
  }

  const missing = boundClassNames.filter((name) => !availableExports.includes(name));
  if (missing.length > 0) {
    nitro.logger.warn(
      `[cloudflare] Wrangler config references the \`${missing.join("`, `")}\` class(es) but they are not exported from \`${prettyPath(exportsEntry)}\`.`
    );
  }

  const names = boundClassNames.filter((name) => availableExports.includes(name));
  if (names.length === 0) {
    return;
  }

  const entry = join(outDir, "worker.mjs");
  await writeFile(entry, composeWorkerSource(devWorkerEntry));

  return {
    entry,
    exports: Object.fromEntries(names.map((name) => [name, boundClasses[name]])),
  };
}

async function getBoundClasses(
  nitro: Nitro
): Promise<Record<string, { type: "DurableObject" | "class" }>> {
  const { config: userConfig } = await readWranglerConfig(nitro);
  const wranglerEnv = nitro.options.cloudflare?.wranglerEnv || process.env.CLOUDFLARE_ENV;
  const doClasses = new Map<string, string>();
  const workflowClasses = new Map<string, string>();
  for (const config of [userConfig, nitro.options.cloudflare?.wrangler]) {
    const resolved = applyWranglerEnv(config, wranglerEnv);
    for (const binding of resolved?.durable_objects?.bindings || []) {
      if (!binding?.name || !binding.class_name) {
        continue;
      }
      if (binding.script_name) {
        doClasses.delete(binding.name);
      } else {
        doClasses.set(binding.name, binding.class_name);
      }
    }
    for (const workflow of resolved?.workflows || []) {
      if (!workflow?.binding || !workflow.class_name) {
        continue;
      }
      if (workflow.script_name) {
        workflowClasses.delete(workflow.binding);
      } else {
        workflowClasses.set(workflow.binding, workflow.class_name);
      }
    }
  }
  return {
    ...Object.fromEntries([...workflowClasses.values()].map((name) => [name, { type: "class" }])),
    ...Object.fromEntries([...doClasses.values()].map((name) => [name, { type: "DurableObject" }])),
  } as Record<string, { type: "DurableObject" | "class" }>;
}

function applyWranglerEnv(
  config: WranglerConfig | undefined,
  env?: string
): WranglerConfig | undefined {
  return env && config?.env?.[env] ? { ...config, ...config.env[env] } : config;
}

async function bundleExportsEntry(entry: string, outFile: string): Promise<string[]> {
  const { rolldown } = await import("rolldown");
  const bundle = await rolldown({
    input: entry,
    platform: "neutral",
    external: /^(cloudflare|workerd|node):/,
    resolve: {
      conditionNames: ["workerd", "worker", "import", "module", "default"],
    },
    logLevel: "silent",
  });
  try {
    const result = await bundle.write({
      file: outFile,
      format: "esm",
      codeSplitting: false,
    });
    const chunk = result.output.find((output) => output.type === "chunk" && output.isEntry);
    return chunk?.type === "chunk" ? chunk.exports : [];
  } finally {
    await bundle.close();
  }
}

function composeWorkerSource(devWorkerEntry: string) {
  return /* js */ `// Generated by nitro
export * from "./exports.mjs";

const devWorkerId = ${JSON.stringify(devWorkerEntry)};
let devWorker, devWorkerPromise;

// The dev worker must be imported dynamically through the unsafe eval binding:
// a plain import() would be statically resolved by miniflare's module crawler,
// which cannot handle its bare imports (at runtime they are resolved by the
// env-runner module fallback service instead).
function loadDevWorker(env) {
  if (env && !globalThis.__ENV_RUNNER_UNSAFE_EVAL__) {
    globalThis.__ENV_RUNNER_UNSAFE_EVAL__ = env.__ENV_RUNNER_UNSAFE_EVAL__;
  }
  return (devWorkerPromise ??= globalThis.__ENV_RUNNER_UNSAFE_EVAL__
    .newAsyncFunction("return import(id)", "loadDevWorker", "id")(devWorkerId)
    .then((mod) => (devWorker = mod)));
}

export async function fetch(request, env, ctx) {
  return (await loadDevWorker(env)).fetch(request, env, ctx);
}

export async function upgrade(context) {
  return (await loadDevWorker()).upgrade(context);
}

export const ipc = {
  async onOpen(ctx) {
    return (await loadDevWorker()).ipc?.onOpen?.(ctx);
  },
  onMessage(message) {
    if (devWorker) {
      devWorker.ipc?.onMessage?.(message);
    } else {
      loadDevWorker().then((mod) => mod.ipc?.onMessage?.(message));
    }
  },
  async onClose() {
    return devWorker?.ipc?.onClose?.();
  },
};
`;
}
